// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyAQxXsGeh_xcM3CZflwYHNBoEfPhFLdTQY",
    authDomain: "out2day-d9410.firebaseapp.com",
    projectId: "out2day-d9410",
    storageBucket: "out2day-d9410.firebasestorage.app",
    messagingSenderId: "382007031902",
    appId: "1:382007031902:web:5fbe10e38a573bd6501ccf",
    measurementId: "G-3MGH8QLBEW",
    databaseURL: "https://out2day-d9410-default-rtdb.firebaseio.com",
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgm9bsgZWlZ-TxoEQiEhurdZ55_G4QUSE',
    appId: '1:382007031902:android:72348b82ff3d061a501ccf',
    messagingSenderId: '382007031902',
    projectId: 'out2day-d9410',
    storageBucket: 'out2day-d9410.firebasestorage.app',
    databaseURL: 'https://out2day-d9410-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUKVfKZrgntn6Ed-57gRtqNRRdKYsJ7ZA',
    appId: '1:304833466102:ios:42c4eca53a016f528be6d7',
    messagingSenderId: '304833466102',
    projectId: 'invoice-generator-9a1a5',
    storageBucket: 'invoice-generator-9a1a5.firebasestorage.app',
    iosBundleId: 'com.example.pdfCreation',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: "AIzaSyAQxXsGeh_xcM3CZflwYHNBoEfPhFLdTQY",
    authDomain: "out2day-d9410.firebaseapp.com",
    projectId: "out2day-d9410",
    storageBucket: "out2day-d9410.firebasestorage.app",
    messagingSenderId: "382007031902",
    appId: "1:382007031902:web:5fbe10e38a573bd6501ccf",
    measurementId: "G-3MGH8QLBEW",
    databaseURL: 'https://out2day-d9410-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: "AIzaSyAQxXsGeh_xcM3CZflwYHNBoEfPhFLdTQY",
    authDomain: "out2day-d9410.firebaseapp.com",
    projectId: "out2day-d9410",
    storageBucket: "out2day-d9410.firebasestorage.app",
    messagingSenderId: "382007031902",
    appId: "1:382007031902:web:5fbe10e38a573bd6501ccf",
    measurementId: "G-3MGH8QLBEW",
    databaseURL: 'https://out2day-d9410-default-rtdb.firebaseio.com',
  );
}
